/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Frontend;

import java.awt.Color;

/**
 *
 * @author Junaid Sultan
 */
public class Mainframe extends javax.swing.JFrame {

    /**
     * Creates new form Mainframe
     */
    public Mainframe() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainTab = new javax.swing.JTabbedPane();
        LoginTab = new javax.swing.JTabbedPane();
        LoginPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        LoginEmail = new javax.swing.JTextField();
        LoginPassword = new javax.swing.JPasswordField();
        LoginButton = new javax.swing.JButton();
        LoginSignupButon = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        BackgroundLogin = new javax.swing.JLabel();
        SingupPanel = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        SignupEmail = new javax.swing.JTextField();
        SignupPassword = new javax.swing.JPasswordField();
        SignupPassword1 = new javax.swing.JPasswordField();
        SignupButton = new javax.swing.JButton();
        LoginSignupButon1 = new javax.swing.JLabel();
        BackgroundSignup = new javax.swing.JLabel();
        Manager = new javax.swing.JPanel();
        ManagerTab = new javax.swing.JTabbedPane();
        Analytics = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        TotalProductsSoldText = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        MostSellingProductText = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        TotalProfitText = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        TotalRegularCustomersText = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        SalesTable = new javax.swing.JTable();
        Products = new javax.swing.JPanel();
        ProductTablePanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        ProductTable = new javax.swing.JTable();
        RefreshProduct = new javax.swing.JButton();
        AddProduct = new javax.swing.JButton();
        UpdateProduct = new javax.swing.JButton();
        Customer = new javax.swing.JPanel();
        CustomerTablePanel = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        CustomerTable = new javax.swing.JTable();
        RefreshCustomer = new javax.swing.JButton();
        AddCustomer = new javax.swing.JButton();
        UpdateCustomer = new javax.swing.JButton();
        Sales = new javax.swing.JPanel();
        SalesTablePanel = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        RefreshSale = new javax.swing.JButton();
        AddSale = new javax.swing.JButton();
        UpdateSale = new javax.swing.JButton();
        ManagerSidePanel3 = new javax.swing.JPanel();
        ManagerSidePanel2 = new javax.swing.JPanel();
        AnalyticsButton = new javax.swing.JButton();
        ProductButton = new javax.swing.JButton();
        CustomerButton = new javax.swing.JButton();
        SaleButton = new javax.swing.JButton();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LoginPanel.setBackground(new java.awt.Color(255, 255, 255));
        LoginPanel.setMaximumSize(new java.awt.Dimension(927, 640));
        LoginPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("Password");
        LoginPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 220, 130, -1));

        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("Email");
        LoginPanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 150, 130, -1));

        LoginEmail.setBackground(new java.awt.Color(51, 51, 51));
        LoginEmail.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        LoginEmail.setForeground(new java.awt.Color(204, 204, 204));
        LoginEmail.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 2, true));
        LoginEmail.setOpaque(true);
        LoginPanel.add(LoginEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 170, 450, 40));

        LoginPassword.setBackground(new java.awt.Color(51, 51, 51));
        LoginPassword.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        LoginPassword.setForeground(new java.awt.Color(204, 204, 204));
        LoginPassword.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 2, true));
        LoginPanel.add(LoginPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 240, 450, 40));

        LoginButton.setBackground(new java.awt.Color(153, 153, 153));
        LoginButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LoginButton.setText("Login");
        LoginButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LoginButton.setFocusable(false);
        LoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginButtonActionPerformed(evt);
            }
        });
        LoginPanel.add(LoginButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 330, 450, 40));

        LoginSignupButon.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LoginSignupButon.setForeground(new java.awt.Color(204, 204, 204));
        LoginSignupButon.setText("Sign up here");
        LoginSignupButon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LoginSignupButon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LoginSignupButonMouseClicked(evt);
            }
        });
        LoginPanel.add(LoginSignupButon, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 380, 80, -1));

        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("Don't have an account?");
        LoginPanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 380, 130, -1));

        BackgroundLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Graphics/login.png"))); // NOI18N
        LoginPanel.add(BackgroundLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(-3, 0, 930, 640));

        LoginTab.addTab("tab1", LoginPanel);

        SingupPanel.setBackground(new java.awt.Color(255, 255, 255));
        SingupPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setForeground(new java.awt.Color(204, 204, 204));
        jLabel5.setText("Email");
        SingupPanel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 130, 130, -1));

        jLabel6.setForeground(new java.awt.Color(204, 204, 204));
        jLabel6.setText("Password");
        SingupPanel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 220, 130, -1));

        jLabel7.setForeground(new java.awt.Color(204, 204, 204));
        jLabel7.setText("Confirm Password");
        SingupPanel.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 300, 130, -1));

        SignupEmail.setBackground(new java.awt.Color(51, 51, 51));
        SignupEmail.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        SignupEmail.setForeground(new java.awt.Color(204, 204, 204));
        SignupEmail.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 2, true));
        SignupEmail.setOpaque(true);
        SingupPanel.add(SignupEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 150, 450, 40));

        SignupPassword.setBackground(new java.awt.Color(51, 51, 51));
        SignupPassword.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        SignupPassword.setForeground(new java.awt.Color(204, 204, 204));
        SignupPassword.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 2, true));
        SingupPanel.add(SignupPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 320, 450, 40));

        SignupPassword1.setBackground(new java.awt.Color(51, 51, 51));
        SignupPassword1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        SignupPassword1.setForeground(new java.awt.Color(204, 204, 204));
        SignupPassword1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 2, true));
        SingupPanel.add(SignupPassword1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 240, 450, 40));

        SignupButton.setBackground(new java.awt.Color(153, 153, 153));
        SignupButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        SignupButton.setText("Confirm");
        SignupButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SignupButton.setFocusable(false);
        SingupPanel.add(SignupButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 420, 450, 40));

        LoginSignupButon1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LoginSignupButon1.setForeground(new java.awt.Color(204, 204, 204));
        LoginSignupButon1.setText("Back");
        LoginSignupButon1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LoginSignupButon1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LoginSignupButon1MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                LoginSignupButon1MousePressed(evt);
            }
        });
        SingupPanel.add(LoginSignupButon1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 540, 40, -1));

        BackgroundSignup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Graphics/login.png"))); // NOI18N
        SingupPanel.add(BackgroundSignup, new org.netbeans.lib.awtextra.AbsoluteConstraints(-3, 0, 930, 640));

        LoginTab.addTab("tab2", SingupPanel);

        MainTab.addTab("tab1", LoginTab);

        Manager.setMaximumSize(new java.awt.Dimension(927, 640));
        Manager.setMinimumSize(new java.awt.Dimension(927, 640));
        Manager.setPreferredSize(new java.awt.Dimension(927, 640));
        Manager.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Analytics.setBackground(new java.awt.Color(255, 255, 255));
        Analytics.setOpaque(false);

        jPanel2.setBackground(new java.awt.Color(0, 0, 0, 200));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Total Products Sold");

        TotalProductsSoldText.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        TotalProductsSoldText.setForeground(new java.awt.Color(255, 255, 255));
        TotalProductsSoldText.setText("1514");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE)
                    .addComponent(TotalProductsSoldText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TotalProductsSoldText, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(0, 0, 0, 200));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Most Selling Product");

        MostSellingProductText.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        MostSellingProductText.setForeground(new java.awt.Color(255, 255, 255));
        MostSellingProductText.setText("Ice Cream Sandwich");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(MostSellingProductText, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MostSellingProductText, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(0, 0, 0, 200));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Total Profit");

        TotalProfitText.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        TotalProfitText.setForeground(new java.awt.Color(255, 255, 255));
        TotalProfitText.setText("$ 273890432");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGap(0, 3, Short.MAX_VALUE)
                        .addComponent(TotalProfitText, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addComponent(TotalProfitText, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(0, 0, 0, 200));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Total Regular Customers");

        TotalRegularCustomersText.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        TotalRegularCustomersText.setForeground(new java.awt.Color(255, 255, 255));
        TotalRegularCustomersText.setText("12");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(0, 9, Short.MAX_VALUE)
                        .addComponent(TotalRegularCustomersText, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addComponent(TotalRegularCustomersText, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        SalesTable.setBackground(new java.awt.Color(0, 0, 0, 100));
        SalesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        SalesTable.setFocusable(false);
        SalesTable.setGridColor(new java.awt.Color(0, 0, 0));
        jScrollPane1.setViewportView(SalesTable);

        javax.swing.GroupLayout AnalyticsLayout = new javax.swing.GroupLayout(Analytics);
        Analytics.setLayout(AnalyticsLayout);
        AnalyticsLayout.setHorizontalGroup(
            AnalyticsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AnalyticsLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(AnalyticsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(AnalyticsLayout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(AnalyticsLayout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        AnalyticsLayout.setVerticalGroup(
            AnalyticsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AnalyticsLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(AnalyticsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(AnalyticsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );

        ManagerTab.addTab("tab1", Analytics);

        Products.setBackground(new java.awt.Color(255, 255, 255));
        Products.setOpaque(false);

        ProductTablePanel.setOpaque(false);

        ProductTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Catagory", "Retail", "Wholesale", "Stock"
            }
        ));
        ProductTable.setShowGrid(true);
        jScrollPane2.setViewportView(ProductTable);

        RefreshProduct.setBackground(new java.awt.Color(51, 51, 51));
        RefreshProduct.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        RefreshProduct.setForeground(new java.awt.Color(255, 255, 255));
        RefreshProduct.setText("Refresh");

        AddProduct.setBackground(new java.awt.Color(51, 51, 51));
        AddProduct.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        AddProduct.setForeground(new java.awt.Color(255, 255, 255));
        AddProduct.setText("Add Product");

        UpdateProduct.setBackground(new java.awt.Color(51, 51, 51));
        UpdateProduct.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        UpdateProduct.setForeground(new java.awt.Color(255, 255, 255));
        UpdateProduct.setText("Update Product");

        javax.swing.GroupLayout ProductTablePanelLayout = new javax.swing.GroupLayout(ProductTablePanel);
        ProductTablePanel.setLayout(ProductTablePanelLayout);
        ProductTablePanelLayout.setHorizontalGroup(
            ProductTablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ProductTablePanelLayout.createSequentialGroup()
                .addGap(0, 30, Short.MAX_VALUE)
                .addGroup(ProductTablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ProductTablePanelLayout.createSequentialGroup()
                        .addComponent(AddProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(UpdateProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ProductTablePanelLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(RefreshProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 748, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        ProductTablePanelLayout.setVerticalGroup(
            ProductTablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ProductTablePanelLayout.createSequentialGroup()
                .addContainerGap(8, Short.MAX_VALUE)
                .addGroup(ProductTablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(AddProduct, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(UpdateProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 484, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RefreshProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );

        javax.swing.GroupLayout ProductsLayout = new javax.swing.GroupLayout(Products);
        Products.setLayout(ProductsLayout);
        ProductsLayout.setHorizontalGroup(
            ProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProductsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ProductTablePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        ProductsLayout.setVerticalGroup(
            ProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProductsLayout.createSequentialGroup()
                .addContainerGap(43, Short.MAX_VALUE)
                .addComponent(ProductTablePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        ManagerTab.addTab("tab2", Products);

        Customer.setBackground(new java.awt.Color(255, 255, 255));
        Customer.setOpaque(false);

        CustomerTablePanel.setOpaque(false);

        CustomerTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Type", "Money Spent", "Sales Done"
            }
        ));
        CustomerTable.setShowGrid(true);
        CustomerTable.setShowHorizontalLines(true);
        CustomerTable.setShowVerticalLines(true);
        jScrollPane3.setViewportView(CustomerTable);

        RefreshCustomer.setBackground(new java.awt.Color(51, 51, 51));
        RefreshCustomer.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        RefreshCustomer.setForeground(new java.awt.Color(255, 255, 255));
        RefreshCustomer.setText("Refresh");
        RefreshCustomer.setFocusable(false);

        AddCustomer.setBackground(new java.awt.Color(51, 51, 51));
        AddCustomer.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        AddCustomer.setForeground(new java.awt.Color(255, 255, 255));
        AddCustomer.setText("Add Customer");
        AddCustomer.setFocusable(false);

        UpdateCustomer.setBackground(new java.awt.Color(51, 51, 51));
        UpdateCustomer.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        UpdateCustomer.setForeground(new java.awt.Color(255, 255, 255));
        UpdateCustomer.setText("Modify Customer");
        UpdateCustomer.setFocusable(false);

        javax.swing.GroupLayout CustomerTablePanelLayout = new javax.swing.GroupLayout(CustomerTablePanel);
        CustomerTablePanel.setLayout(CustomerTablePanelLayout);
        CustomerTablePanelLayout.setHorizontalGroup(
            CustomerTablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CustomerTablePanelLayout.createSequentialGroup()
                .addGap(0, 35, Short.MAX_VALUE)
                .addGroup(CustomerTablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CustomerTablePanelLayout.createSequentialGroup()
                        .addComponent(RefreshCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(CustomerTablePanelLayout.createSequentialGroup()
                        .addGroup(CustomerTablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(CustomerTablePanelLayout.createSequentialGroup()
                                .addComponent(AddCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(UpdateCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 740, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(15, Short.MAX_VALUE))))
        );
        CustomerTablePanelLayout.setVerticalGroup(
            CustomerTablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CustomerTablePanelLayout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addGroup(CustomerTablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UpdateCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 484, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RefreshCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout CustomerLayout = new javax.swing.GroupLayout(Customer);
        Customer.setLayout(CustomerLayout);
        CustomerLayout.setHorizontalGroup(
            CustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(CustomerTablePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        CustomerLayout.setVerticalGroup(
            CustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CustomerLayout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addComponent(CustomerTablePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        ManagerTab.addTab("tab3", Customer);

        Sales.setBackground(new java.awt.Color(255, 255, 255));
        Sales.setOpaque(false);

        SalesTablePanel.setOpaque(false);

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Date", "Customer", "Profit", "Products Sold"
            }
        ));
        jScrollPane4.setViewportView(jTable4);

        RefreshSale.setBackground(new java.awt.Color(51, 51, 51));
        RefreshSale.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        RefreshSale.setForeground(new java.awt.Color(255, 255, 255));
        RefreshSale.setText("Refesh");

        AddSale.setBackground(new java.awt.Color(51, 51, 51));
        AddSale.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        AddSale.setForeground(new java.awt.Color(255, 255, 255));
        AddSale.setText("New Sale");

        UpdateSale.setBackground(new java.awt.Color(51, 51, 51));
        UpdateSale.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        UpdateSale.setForeground(new java.awt.Color(255, 255, 255));
        UpdateSale.setText("Delete Sale");

        javax.swing.GroupLayout SalesTablePanelLayout = new javax.swing.GroupLayout(SalesTablePanel);
        SalesTablePanel.setLayout(SalesTablePanelLayout);
        SalesTablePanelLayout.setHorizontalGroup(
            SalesTablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SalesTablePanelLayout.createSequentialGroup()
                .addGap(0, 25, Short.MAX_VALUE)
                .addGroup(SalesTablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SalesTablePanelLayout.createSequentialGroup()
                        .addComponent(AddSale, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(UpdateSale, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(RefreshSale, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 753, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        SalesTablePanelLayout.setVerticalGroup(
            SalesTablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SalesTablePanelLayout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addGroup(SalesTablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(AddSale, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(UpdateSale, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 484, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RefreshSale, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout SalesLayout = new javax.swing.GroupLayout(Sales);
        Sales.setLayout(SalesLayout);
        SalesLayout.setHorizontalGroup(
            SalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SalesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(SalesTablePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        SalesLayout.setVerticalGroup(
            SalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SalesLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(SalesTablePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        ManagerTab.addTab("tab4", Sales);

        Manager.add(ManagerTab, new org.netbeans.lib.awtextra.AbsoluteConstraints(133, -35, 790, 700));

        ManagerSidePanel3.setBackground(new java.awt.Color(204, 204, 204));
        ManagerSidePanel3.setFocusable(false);

        javax.swing.GroupLayout ManagerSidePanel3Layout = new javax.swing.GroupLayout(ManagerSidePanel3);
        ManagerSidePanel3.setLayout(ManagerSidePanel3Layout);
        ManagerSidePanel3Layout.setHorizontalGroup(
            ManagerSidePanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        ManagerSidePanel3Layout.setVerticalGroup(
            ManagerSidePanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 680, Short.MAX_VALUE)
        );

        Manager.add(ManagerSidePanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 0, 10, 680));

        ManagerSidePanel2.setBackground(new java.awt.Color(51, 51, 51));

        AnalyticsButton.setBackground(new java.awt.Color(51, 51, 51));
        AnalyticsButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        AnalyticsButton.setForeground(new java.awt.Color(255, 255, 255));
        AnalyticsButton.setText("Analytics");
        AnalyticsButton.setFocusable(false);
        AnalyticsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnalyticsButtonActionPerformed(evt);
            }
        });

        ProductButton.setBackground(new java.awt.Color(51, 51, 51));
        ProductButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        ProductButton.setForeground(new java.awt.Color(255, 255, 255));
        ProductButton.setText("Products");
        ProductButton.setFocusable(false);
        ProductButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProductButtonActionPerformed(evt);
            }
        });

        CustomerButton.setBackground(new java.awt.Color(51, 51, 51));
        CustomerButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        CustomerButton.setForeground(new java.awt.Color(255, 255, 255));
        CustomerButton.setText("Customers");
        CustomerButton.setFocusable(false);
        CustomerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CustomerButtonActionPerformed(evt);
            }
        });

        SaleButton.setBackground(new java.awt.Color(51, 51, 51));
        SaleButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        SaleButton.setForeground(new java.awt.Color(255, 255, 255));
        SaleButton.setText("Sales");
        SaleButton.setFocusable(false);
        SaleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaleButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ManagerSidePanel2Layout = new javax.swing.GroupLayout(ManagerSidePanel2);
        ManagerSidePanel2.setLayout(ManagerSidePanel2Layout);
        ManagerSidePanel2Layout.setHorizontalGroup(
            ManagerSidePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AnalyticsButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(ProductButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(CustomerButton, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
            .addComponent(SaleButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        ManagerSidePanel2Layout.setVerticalGroup(
            ManagerSidePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ManagerSidePanel2Layout.createSequentialGroup()
                .addContainerGap(62, Short.MAX_VALUE)
                .addComponent(AnalyticsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ProductButton, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(CustomerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(SaleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );

        Manager.add(ManagerSidePanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 140, 680));

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Graphics/manager.png"))); // NOI18N
        Background.setText("jLabel3");
        Manager.add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 930, 670));

        MainTab.addTab("tab2", Manager);

        getContentPane().add(MainTab, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -72, -1, 690));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LoginSignupButon1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoginSignupButon1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_LoginSignupButon1MousePressed

    private void LoginSignupButon1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoginSignupButon1MouseClicked
        LoginTab.setSelectedIndex(0);
    }//GEN-LAST:event_LoginSignupButon1MouseClicked

    private void LoginSignupButonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoginSignupButonMouseClicked
        LoginTab.setSelectedIndex(1);
    }//GEN-LAST:event_LoginSignupButonMouseClicked

    private void LoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginButtonActionPerformed
        MainTab.setSelectedIndex(1);
    }//GEN-LAST:event_LoginButtonActionPerformed

    private void AnalyticsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnalyticsButtonActionPerformed
        ManagerTab.setSelectedIndex(0);
    }//GEN-LAST:event_AnalyticsButtonActionPerformed

    private void ProductButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProductButtonActionPerformed
        ManagerTab.setSelectedIndex(1);
    }//GEN-LAST:event_ProductButtonActionPerformed

    private void CustomerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CustomerButtonActionPerformed
        ManagerTab.setSelectedIndex(2);
    }//GEN-LAST:event_CustomerButtonActionPerformed

    private void SaleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaleButtonActionPerformed
        ManagerTab.setSelectedIndex(3);
    }//GEN-LAST:event_SaleButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Mainframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Mainframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Mainframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Mainframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Mainframe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddCustomer;
    private javax.swing.JButton AddProduct;
    private javax.swing.JButton AddSale;
    private javax.swing.JPanel Analytics;
    private javax.swing.JButton AnalyticsButton;
    private javax.swing.JLabel Background;
    private javax.swing.JLabel BackgroundLogin;
    private javax.swing.JLabel BackgroundSignup;
    private javax.swing.JPanel Customer;
    private javax.swing.JButton CustomerButton;
    private javax.swing.JTable CustomerTable;
    private javax.swing.JPanel CustomerTablePanel;
    private javax.swing.JButton LoginButton;
    private javax.swing.JTextField LoginEmail;
    private javax.swing.JPanel LoginPanel;
    private javax.swing.JPasswordField LoginPassword;
    private javax.swing.JLabel LoginSignupButon;
    private javax.swing.JLabel LoginSignupButon1;
    private javax.swing.JTabbedPane LoginTab;
    private javax.swing.JTabbedPane MainTab;
    private javax.swing.JPanel Manager;
    private javax.swing.JPanel ManagerSidePanel2;
    private javax.swing.JPanel ManagerSidePanel3;
    private javax.swing.JTabbedPane ManagerTab;
    private javax.swing.JLabel MostSellingProductText;
    private javax.swing.JButton ProductButton;
    private javax.swing.JTable ProductTable;
    private javax.swing.JPanel ProductTablePanel;
    private javax.swing.JPanel Products;
    private javax.swing.JButton RefreshCustomer;
    private javax.swing.JButton RefreshProduct;
    private javax.swing.JButton RefreshSale;
    private javax.swing.JButton SaleButton;
    private javax.swing.JPanel Sales;
    private javax.swing.JTable SalesTable;
    private javax.swing.JPanel SalesTablePanel;
    private javax.swing.JButton SignupButton;
    private javax.swing.JTextField SignupEmail;
    private javax.swing.JPasswordField SignupPassword;
    private javax.swing.JPasswordField SignupPassword1;
    private javax.swing.JPanel SingupPanel;
    private javax.swing.JLabel TotalProductsSoldText;
    private javax.swing.JLabel TotalProfitText;
    private javax.swing.JLabel TotalRegularCustomersText;
    private javax.swing.JButton UpdateCustomer;
    private javax.swing.JButton UpdateProduct;
    private javax.swing.JButton UpdateSale;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable4;
    // End of variables declaration//GEN-END:variables
}
